### ISSUE TITLE
Log window opens when LogType=none

### ISSUE THREAD

**Issue by Nicholas-Schaub** [usnistgov/MIST#1]
I'm running MIST from a macro, and I set logtype=none in the options string. Using this option, the log window still opens, but nothing is printed in the log window. Since my macro runs MIST on multiple images, closing the window only works until MIST is finished stitching the current image. The log window re-opens when MIST runs on the next image.

**Comment by mmajurski** [comment]
Remove a few log commands that happen before the log level is updated with the users value. This should prevent the log window from opening at all when the user selects LogLevel = None.

This change has been pushed to the Fiji update site.
