### ISSUE TITLE
Not enough memory to create output stitched image.

### ISSUE THREAD

**Issue by Tommy7013** [usnistgov/MIST#10]
Hi, 
  Something wrong to the MIST, when I want to stitch 5000 RGB pictures, I have enogh disk , swap and virtual memory. Could you help me to figure it out?

Thanks 
Tommy

**Comment by tblattner** [comment]
Hi Tommy,

Unfortunately the current maximum number of pixels of an output image from the Java code is 2,147,483,647 pixels. I will pass this onto my colleague, who I believe has an external script that can be used to assemble larger images using the global position list.

Regards,
Tim

**Comment by mmajurski** [comment]
If Matlab is a language you can use, I had a script for assembling arbitrarily sized images (so long as they fit in system memory).

I have not run this code in literally years, so its a coin flip as to whether it still works.

~Michael

[assemble_stitching.zip](https://github.com/usnistgov/MIST/files/3281573/assemble_stitching.zip)

**Comment by Tommy7013** [comment]
Hi, 
   Got you. Thank you very much. It's really a big help.


Thanks 
Tommy 



--




4203 Training building #4
Shanghai University of Engineering Science

333 Longteng Road, Songjiang District,

Shanghai, 201620,China
Tel:+8618516731643
email:tommy_crazy@163.com

在 2019-06-12 21:11:06，"Timothy Blattner" <notifications@github.com> 写道：


Hi Tommy,

Unfortunately the current maximum number of pixels of an output image from the Java code is 2,147,483,647 pixels. I will pass this onto my colleague, who I believe has an external script that can be used to assemble larger images using the global position list.

Regards,
Tim

**Comment by Tommy7013** [comment]
Hi,  
   Michael, thank you very much. It's really a big help. And thanks for you guys' open source.




 Best wishes
Thanks
 
Tommy




--




4203 Training building #4
Shanghai University of Engineering Science

333 Longteng Road, Songjiang District,

Shanghai, 201620,China
Tel:+8618516731643
email:tommy_crazy@163.com

At 2019-06-12 21:45:55, "Michael Majurski" <notifications@github.com> wrote:


If Matlab is a language you can use, I had a script for assembling arbitrarily sized images (so long as they fit in system memory).

I have not run this code in literally years, so its a coin flip as to whether it still works.

~Michael

assemble_stitching.zip
