### ISSUE TITLE
Stitching two sets of images from different times in experiment

### ISSUE THREAD

**Issue by julianaspector** [usnistgov/MIST#11]
I have 2 sets of 6 images that were taken at the same locations at different times in an experiment.

Trying to stitch together each set and subtract the images as rasters. The stitched sets end up being different lengths, even if I set the horizontal overlap to be the same percentage for both sets (which they theoretically should be). 
[Image_set_1.zip](https://github.com/usnistgov/MIST/files/3508147/Image_set_1.zip)
[Image_set_2.zip](https://github.com/usnistgov/MIST/files/3508148/Image_set_2.zip)

More details about my setup in MIST:

Filename Pattern Type: Row-Column
Starting Point: Upper Left
Grid Width: 6
Grid Height: 1
Column Start Tile: 4
Row Start Tile: 1
Timeslices: 0

Filename Pattern: img_r{r}_c{c}.tif

Blending Mode: Linear
Subgrid: Use Full Grid

Horizontal overlap: 60% (estimated)
Translation Refinement Method: Single Hill Climb
Stitching Program: FFTW

**Comment by mmajurski** [comment]
Can you clarify what you mean by "The stitched sets end up being different lengths"? 

If you are stitching two different grids of images, I would expect that subtle differences in the input image would produce stitched images of different width and height. At the very least by a few pixels. 

If you need the exact same image size, you could try assembling the second set with the translations computed from the first set.

Finally, if you acquired the images at two different times, no physical system is perfect, so I don't expect the tiles are going to be in the same 'localtion' with pixel level accuracy. There will often be single digit pixel shifts between images (if the stage is well calibrated) and larger shifts with less well calibrated equipment.
