### ISSUE TITLE
Stitch image at different FOV

### ISSUE THREAD

**Issue by jurneo** [usnistgov/MIST#13]
I have a general question:
Can this stitch image at different FOV (magnification) ? I could not find the information at the wiki site. Thanks.

**Comment by kvinicki** [comment]
Maybe this could be possible with additional image pre-processing. But, why would you do that?

**Comment by mmajurski** [comment]
MIST does not support multiple magnification images. You would need to project all your images into a single magnification grid with repeatability overlaps before MIST would be able to operate on the data.
