### ISSUE TITLE
Issue with installation: no module named numpy

### ISSUE THREAD

**Issue by cdtcoustet** [usnistgov/MIST#37]
Hello, 
I've been trying to install MIST for a couple of hours but "ImportError: no module named numpy" keep returning to me. I use the version 1.54d of Fiji on MacOS and installed both fftw and Cuda (but none of them is working). I read that similar issues are usually associated with the newer versions of Jython but I can't seem to find a solution to overcome this message. Does anyone have any idea how I could solve this issue?
Thank you very much in advance for your help!

**Comment by cdtcoustet** [comment]
Thank you so much for your help! Here are the screenshots of the content of MIST folder (which I placed in the "plugin" repository) and the issue returned when I try to launch the plugin with FIJI: 
![Capture d’écran 2023-04-28 à 10 32 42](https://user-images.githubusercontent.com/131789089/235097971-7f6f61e6-099b-426c-90f5-806500224cf5.png)
![Capture d’écran 2023-04-28 à 10 33 58](https://user-images.githubusercontent.com/131789089/235097974-8fb04319-b3f8-4507-9849-c784f536774f.png)
And I am not able to open the MIST interface.

**Comment by tblattner** [comment]
Did you follow these instructions? https://github.com/USNISTGOV/MIST/wiki/Install-Guide

**Comment by cdtcoustet** [comment]
Oops, you were right, I skipped one step and now everything works well... Thanks for your time!
