### ISSUE TITLE
CUDA toolkit version

### ISSUE THREAD

**Issue by smith6jt-cop** [usnistgov/MIST#41]
Hello,

Your instructions at https://github.com/USNISTGOV/MIST/wiki/Install-Guide indicate to use toolkit 9.0, but the help documentation in the FIJI plugin indicates toolkit 6.5.  Can you please clarify?

Thanks

**Comment by smith6jt-cop** [comment]
Based on Windows version

**Comment by tblattner** [comment]
Hello,

Unfortunately the CUDA version of MIST is no longer supported. There were issues related to synchronization introduced in newer versions of the GPU architecture that required us to rewrite some of the CUDA kernels. We have not had the cycles to add this capability. Thus far the multi-threading with FFTW has sufficiently kept up with disk I/O, and is scalable to the number of CPU cores on a machine.

I have added this note into the Wiki.

**Comment by smith6jt-cop** [comment]
Thank you for the information!  Yes the FFTW is working very well in our hands.

Thanks,

Justin Smith, PhD
Dept of Pathology, Immunology, and Laboratory Medicine
UF Diabetes Institute
College of Medicine
1275 Center Drive, 5th Floor
Gainesville, FL 32610
