### ISSUE TITLE
Error in paper (v2017-03-13) algo 12

### ISSUE THREAD

**Issue by RobertBaruch** [usnistgov/MIST#6]
In algorithm 12 (computeMle), you have:

probUniform <- 1/100
l <- p * probUniform + ...

From examination of the code, I think you meant:

p <- 1/100
l <- p * model.probUniform

**Comment by mmajurski** [comment]
Very sharp eyes. There was an issue with merging two versions of the documentation. The copy I pushed should be correct.

Thank you,
Michael
